server:
  port: 8090
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  devtools:
    restart:
      eanbled: false
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #
  #    # H2 database configuration.
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:file:${halo.work-dir}/db/halo
  #    username: admin
  #    password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.5.15.254:3306/halodb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&nullCatalogMeansCurrent=true
      username: videt
      password: "123456"
      initial-size: 1
      min-idle: 10
      max-active: 20
      max-wait: -1
      validation-query: SELECT 1
      validation-query-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
logging:
  level:
    run.halo.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${halo.work-dir}/logs

springfox:
  documentation:
    enabled: false

halo:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/.halo/